FROM node:20-alpine

# Instalar dependências necessárias
RUN apk add --no-cache python3 make g++

WORKDIR /app

# Instalar dependências globais
RUN npm install -g @nestjs/cli

# Copiar arquivos de dependências
COPY package*.json ./

# Instalar dependências
RUN npm install

# Expor porta
EXPOSE 3000

# Comando para iniciar a aplicação em modo de desenvolvimento
CMD ["npm", "run", "start:dev"]
